import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js'
import { acquireCar as originalAcquire, disposeCarScene } from '../../src/three/car-loader.mjs'
import { configureAuthoredLiveryLoader, assertAuthoredTextures } from '../../src/three/authored-livery.mjs'
const basePath='/models/mercedes-w17-russell.glb',targetPath='/models/mercedes-w17-antonelli.glb'
let cache
const diagnostics=window.__skinLab={events:[],baseLoads:0,skinLoads:0}
Object.defineProperty(diagnostics,'refs',{enumerable:true,get:()=>cache?.refs??0}); function snapshot(scene){const geometries=new Set(),textures=new Set(),materials=new Set();scene.traverse(n=>{if(!n.isMesh)return;geometries.add(n.geometry);for(const m of Array.isArray(n.material)?n.material:[n.material]){materials.add(m);for(const v of Object.values(m))if(v?.isTexture)textures.add(v)}});return{geometries:geometries.size,textures:textures.size,materials:[...materials].map(m=>({name:m.name,alpha:m.transparent,opacity:m.opacity,roughness:m.roughness,metalness:m.metalness,map:m.map&&{channel:m.map.channel,flipY:m.map.flipY,colorSpace:m.map.colorSpace,width:m.map.image.width,height:m.map.image.height,wrapS:m.map.wrapS,wrapT:m.map.wrapT,minFilter:m.map.minFilter,magFilter:m.map.magFilter}}))}}
function schedule(entry){clearTimeout(entry.timer);if(entry.refs)return;entry.timer=setTimeout(async()=>{await Promise.allSettled([entry.base,entry.skin].filter(Boolean));if(entry.refs||cache!==entry)return;cache=undefined;if(entry.skinResult){for(const m of entry.skinResult.materials)m.dispose();for(const t of entry.skinResult.changedTextures)t.dispose()}if(entry.baseResult)disposeCarScene(entry.baseResult.scene);diagnostics.events.push({event:'disposed',at:performance.now()})},1500)}
function getCache(){if(cache)return cache;const entry={refs:0};cache=entry;const loader=new GLTFLoader();configureAuthoredLiveryLoader(loader);diagnostics.baseLoads++;entry.base=loader.loadAsync(basePath).then(result=>{assertAuthoredTextures(result);entry.baseResult=result;return result});return entry}
async function getSkin(entry){if(!entry.skin)entry.skin=(async()=>{const base=await entry.base;diagnostics.skinLoads++;const loader=new GLTFLoader();loader.register(parser=>({name:'F1TechLabSharedTextures',loadTexture(index){return parser.json.textures[index].source===6?null:base.parser.getDependency('texture',index)}}));configureAuthoredLiveryLoader(loader);const parsed=await loader.loadAsync('/__skin-assets/antonelli.gltf');const materials=await parsed.parser.getDependencies('material'); for(let i=0;i<materials.length;i++)if(parsed.parser.json.materials[i].pbrMetallicRoughness?.baseColorTexture&&!materials[i].map)throw Error('Lab texture decode failed: '+materials[i].name);const scene=base.scene.clone(true);const replacements=new Map();scene.traverse(n=>{if(!n.isMesh)return;const convert=m=>{const index=base.parser.associations.get(m)?.materials;if(index===undefined)throw Error('Missing material association');if(parsed.parser.json.textures[parsed.parser.json.materials[index].pbrMetallicRoughness?.baseColorTexture?.index]?.source!==6)return m;if(!replacements.has(m)){const clone=m.clone();clone.map=materials[index].map;replacements.set(m,clone)}return replacements.get(m)};n.material=Array.isArray(n.material)?n.material.map(convert):convert(n.material)});const changedTextures=new Set();for(const m of materials)for(const value of Object.values(m))if(value?.isTexture&&[6,7,8,9].includes(parsed.parser.associations.get(value)?.textures))changedTextures.add(value);entry.skinResult={materials:[...materials,...replacements.values()],changedTextures};const baseMeshes=[],skinMeshes=[];base.scene.traverse(n=>{if(n.isMesh)baseMeshes.push(n)});scene.traverse(n=>{if(n.isMesh)skinMeshes.push(n)});diagnostics.geometryShared=baseMeshes.length===skinMeshes.length&&baseMeshes.every((n,i)=>n.geometry===skinMeshes[i].geometry);assertAuthoredTextures({...base,scene});return{...base,scene}})();return entry.skin}
export function acquireCar(path){if(!import.meta.env.DEV||new URLSearchParams(location.search).get('skinLab')!=='1'||![basePath,targetPath].includes(path))return originalAcquire(path);const entry=getCache();entry.refs++;clearTimeout(entry.timer);let released=false;const start=performance.now();const ready=(path===basePath?entry.base:getSkin(entry)).then(result=>{diagnostics.events.push({path,ms:performance.now()-start,at:performance.now(),...snapshot(result.scene)});return result});return{ready,release(){if(released)return;released=true;entry.refs--;schedule(entry)}}}



